system:
    debug: true
    development: true
mendeley:
    id:
    secret:
scopus:
    key:
@import:
    - database/syllabus.yml
    - database/paper.yml
    - database/social.yml
    - database/scholar.yml
    - database/thesis.yml
    - database/wiki.yml
    - database/tci.yml
    - database/wos.yml
    - database/scopus.yml
    - database/mendeley.yml
    - database/webometrics.yml